# Generated by Django 4.2.7 on 2023-11-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.CharField(max_length=250)),
                ('pic', models.ImageField(upload_to='photo')),
                ('detail', models.TextField()),
            ],
        ),
    ]
